## Configuration for the training, evaluation
samples:
  # - name: e
  #   label : 0
  #   path: /home/chyoo/work/KNO_reconstruction/KNO_reconstruction/test_data/elec
  - name: e
    label : 0
    path: /tmpdata/elec/
  - name: e
    label : 0
    path: /tmpdata/elec_2/

training:
    nDataLoaders : 4
    splitFractions : [0.8, 0.1] ## training set, validation set. (test set is the reminders)
    epoch : 300
    batch : 25
    learningRate : 0.001
    randomSeed : 12346
